### ISSUE TITLE
design file verder uitwerken voor 2de ontwerp met een animatie

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#7]
- [ ] animatie voorbeeld gevonden https://github.com/yujing-student/your-tribe-for-life-profile-card/issues/7#issuecomment-2345572479

- [ ] visuele schets gemaakt 2de ontwerp https://github.com/yujing-student/your-tribe-for-life-profile-card/issues/7#issuecomment-2348321502

- [ ] breakdownschets gemaakt 2de ontwerp https://github.com/yujing-student/your-tribe-for-life-profile-card/issues/7#issuecomment-2357871335

dit was het eerste design
https://www.figma.com/design/Q9Su8EOrx985SuIz2yw0Hz/design-file-sprint-13?node-id=0-1&m=dev&t=jHmfNPcFjvkp60yI-1

![Image](https://github.com/user-attachments/assets/6cb24cdd-bcf1-4353-bcc6-5b3c62f5d76f)

uml diagram :https://www.figma.com/design/WjGGYH7NbZvEW88RYC0Xyl/uml-diagram-sprint-13?node-id=1-5&m=dev&t=ccEVf12z1gRxzlAC-1

**Comment by yujing-student** [comment]
https://blog.hubspot.com/website/css-fade-in 

hiernaar kijken

**Comment by yujing-student** [comment]
![Image](https://github.com/user-attachments/assets/34296342-00e0-4ea3-9427-d5bf7a950715)

https://www.figma.com/design/dtWe8NphDJmwGrjyzw3whR/2de-versie-schets-sprint-13?node-id=0-1&m=dev&t=S1h6ufMWVPEk2I2D-1

als je op de button druk voor meer info klikt dan verschijnt er een nieuw blok

**Comment by yujing-student** [comment]
breakdownschets op mobiel 

![image](https://github.com/user-attachments/assets/847b77e9-19f8-4945-b8a9-09fe160b1603)

breakdownschets desktop

![image](https://github.com/user-attachments/assets/f48fb658-848f-49c4-898c-7369f1166944)


onthouden dat de tekst h2 of p in 1 frame moet zodat het herbruikbaar is en dat het niet als losse elementen zijn

![image](https://github.com/user-attachments/assets/798f62ba-5a66-4112-8033-b46dc29f67c0)

maar eerder dit
![image](https://github.com/user-attachments/assets/792d5725-9bcf-4857-9826-1230e8305acf)
